[platformio]
extra_configs = ../../platformio/platformio.ini
default_envs  = esp32s3sense

[env:esp32dev]
extends        = esp32_microros_wifi
platform       = espressif32
board          = esp32dev
build_flags    =
    ${esp32_microros_wifi.build_flags}
    -DLED_BUILTIN=2
    -DENV_ESP32DEV
    -DDEBUG_TRANSPORT_SERIAL
    -DDEBUG_TRANSPORT_MICROROS
    -DDEBUG_LEVEL=4
    -DBRIDGE_ENABLE_HEARTBEAT=1
    -DBRIDGE_ENABLE_DEBUG=1

[env:esp32s3sense]
extends        = esp32_microros_wifi
platform       = espressif32
board          = seeed_xiao_esp32s3
build_flags    =
    ${esp32_microros_wifi.build_flags}
    -DENV_ESP32S3SENSE
    -DDEBUG_TRANSPORT_SERIAL
    -DDEBUG_TRANSPORT_MICROROS
    -DDEBUG_LEVEL=4
    -DBRIDGE_ENABLE_HEARTBEAT=1
    -DBRIDGE_ENABLE_DEBUG=1
