; 0. Default envs
[platformio]
default_envs = 
    esp32s3sense
extra_configs = ../../platformio/network_config.ini

; 1. Definitions, shared variables
[common]
; Force C++ 17
build_flags =
    -std=gnu++17
    -DTHREADING_SCHEME_ESP_MODERN
build_unflags = -std=gnu++11
; Define common shared libs here
lib_base =
    https://github.com/adafruit/Adafruit_BNO08x.git#0301e6d
    https://github.com/IEEE-UCF/SEC-Base-Classes.git#a5f8c9f
    https://github.com/pfeerick/elapsedMillis.git#8be9e66
    https://github.com/h2zero/NimBLE-Arduino#8370464
    fastled/FastLED @ ^3.9.0
    
; 2. Global settings
[env]
monitor_speed = 921600
lib_deps = ${common.lib_base}

; 3. Base board configurations
[esp32_microros_wifi]
framework = arduino
board_microros_distro = jazzy
board_microros_transport = wifi
lib_extra_dirs =
    ../../libs_external/esp32
    ../../lib/
lib_deps = ${common.lib_base}
build_unflags = ${common.build_unflags}
build_flags =
    ${common.build_flags}
    -DMICRO_ROS_TRANSPORT_ARDUINO_WIFI
    '-DAGENT_IP=${network.agent_ip}'
    '-DAGENT_PORT=${network.agent_port}'
    '-DWIFI_SSID="${network.wifi_ssid}"'
    '-DWIFI_PASSWORD="${network.wifi_password}"'
    '-DSTATIC_IP=${network.static_ip}'
    '-DGATEWAY=${network.gateway}'
    '-DSUBNET=${network.subnet}'

[esp32_microros_serial]
framework = arduino
board_microros_distro = jazzy
board_microros_transport = serial
lib_extra_dirs =
   ../../libs_external/esp32
   ../../lib/
lib_deps = ${common.lib_base}
build_unflags = ${common.build_unflags}
build_flags =
    ${common.build_flags}
    -DMICRO_ROS_TRANSPORT_ARDUINO_SERIAL

; 4. Board environments
[env:esp32dev]
extends = esp32_microros_wifi
platform = espressif32
board = esp32dev
build_flags =
    ${esp32_microros_wifi.build_flags}
    -DLED_BUILTIN=2
    -DENV_ESP32DEV
    -DDEBUG_TRANSPORT_SERIAL
    -DDEBUG_TRANSPORT_BLUETOOTH
    -DDEBUG_TRANSPORT_MICROROS
    -DDEBUG_LEVEL=4
    -DBRIDGE_ENABLE_HEARTBEAT=1
    -DBRIDGE_ENABLE_GYRO=1
    -DBRIDGE_ENABLE_BATTERY=1
    -DBRIDGE_ENABLE_DEBUG=1

[env:esp32s3sense]
extends = esp32_microros_wifi
platform = espressif32
board = seeed_xiao_esp32s3
build_flags =
    ${esp32_microros_wifi.build_flags}
    -DENV_ESP32S3SENSE
    -DDEBUG_TRANSPORT_SERIAL
    -DDEBUG_TRANSPORT_BLUETOOTH
    -DDEBUG_TRANSPORT_MICROROS
    -DDEBUG_LEVEL=4
    -DBRIDGE_ENABLE_HEARTBEAT=1
    -DBRIDGE_ENABLE_GYRO=1
    -DBRIDGE_ENABLE_BATTERY=1
    -DBRIDGE_ENABLE_DEBUG=1

[env:esp32devserial]
extends = esp32_microros_serial
platform = espressif32
board = esp32dev
build_flags =
    ${esp32_microros_serial.build_flags}
    -DLED_BUILTIN=2
    -DENV_ESP32DEV
    -DDEBUG_TRANSPORT_BLUETOOTH
    -DDEBUG_TRANSPORT_MICROROS
    -DDEBUG_LEVEL=4
    -DBRIDGE_ENABLE_HEARTBEAT=1
    -DBRIDGE_ENABLE_GYRO=1
    -DBRIDGE_ENABLE_BATTERY=1
    -DBRIDGE_ENABLE_DEBUG=1

[env:esp32s3senseserial]
extends = esp32_microros_serial
platform = espressif32
board = seeed_xiao_esp32s3
build_flags =
    ${esp32_microros_serial.build_flags}
    -DENV_ESP32S3SENSE
    -DDEBUG_TRANSPORT_BLUETOOTH
    -DDEBUG_TRANSPORT_MICROROS
    -DDEBUG_LEVEL=4
    -DBRIDGE_ENABLE_HEARTBEAT=1
    -DBRIDGE_ENABLE_GYRO=1
    -DBRIDGE_ENABLE_BATTERY=1
    -DBRIDGE_ENABLE_DEBUG=1
